name: Demo-Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Print multiple words
      run: |
       echo "Hello-word"
       echo "Hi"
       echo "Welcome to Github-Actions"


    - name: Cloning the github code
      run: |
        git clone https://github.com/SanthoshKumar1234/simple-springboot-app.git
        cd simple-springboot-app/simple-springboot-app
        mvn install
        

  test:

      runs-on: ubuntu-latest

      steps:

      - name: Test
        run: |
          git clone https://github.com/SanthoshKumar1234/simple-springboot-app.git
          cd  simple-springboot-app/simple-springboot-app
          mvn test   